### ISSUE TITLE
Possible security issue on Password Reset

### ISSUE THREAD

**Issue by ctolkien** [KrisJanssen/Umbraco7-Standard-Membership#1]
Unless I'm overlooking something...

https://github.com/KrisJanssen/Umbraco7-Standard-Membership/blob/master/U7StandardMembership/Controllers/SurfaceControllers/AuthSurfaceController.cs#L191

The Reset GUID is not a guid at all, but a DateTime stamp, this is then used to verify the user in the `HandleResetPassword` method. Because an attacker will know what this timestamp is to probably within 500ms, there are at max 500 different combinations as to what it could be. 

This would then be trivial to brute force and reset the password.

Am working on am implementation for a site that reimplements this differently however will take a bit of time to clean it up.

**Comment by KrisJanssen** [comment]
Thanks for the feedback. I had also already been wondering about that.

Since I want to turn this project into a generally useful package for Umbraco 7, not just a minimal example, I'll definitely also look into this.

**Comment by KrisJanssen** [comment]
At first glance, we have this:

http://msdn.microsoft.com/en-us/library/webmatrix.webdata.websecurity.generatepasswordresettoken(v=vs.111).aspx

So no need re-inventing the wheel :)

I'll get some of that stuff in later today.

**Comment by ctolkien** [comment]
Yep, it would be great to have an Umbraco package that you could just drop in to add the basic membership components, unfortunately I'm under the realities of a deadline at the moment, so the implementation is specific to the current site. Will see what I can do to help once that is out of the way.
